-- =============================================================================
--  ASSET KANTORKU — Skema Database PostgreSQL (>= 13)
--  Laravel 13 monolith · RBAC · Procurement → Assignment/Loan → Disposal
--
--  Cara pakai:
--    createdb -U postgres asset_kantorku
--    psql -U postgres -d asset_kantorku -f database/sql/asset_kantorku.sql
--
--  File ini membuat seluruh tabel (termasuk tabel bawaan Laravel: sessions,
--  cache, jobs, notifications), constraint, trigger integritas, data RBAC, dan
--  data awal (demo). Jalankan pada database KOSONG.
--
--  Akun demo (password: "password") — WAJIB diganti setelah instalasi:
--    sysadmin@kantorku.test   → System Administrator
--    admin.aset@kantorku.test → Asset Administrator
--    direktur@kantorku.test   → Manager (approver eskalasi)
--    manager.it@kantorku.test → Manager
--    staff@kantorku.test      → Staff
--    auditor@kantorku.test    → Auditor
-- =============================================================================

BEGIN;

SET client_min_messages = warning;

-- Dibutuhkan untuk exclusion constraint (asset_id WITH =, range WITH &&)
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- =============================================================================
-- 1. TABEL FRAMEWORK LARAVEL
-- =============================================================================

CREATE TABLE sessions (
    id              VARCHAR(255) PRIMARY KEY,
    user_id         BIGINT NULL,
    ip_address      VARCHAR(45) NULL,
    user_agent      TEXT NULL,
    payload         TEXT NOT NULL,
    last_activity   INTEGER NOT NULL
);
CREATE INDEX sessions_user_id_index ON sessions (user_id);
CREATE INDEX sessions_last_activity_index ON sessions (last_activity);

CREATE TABLE password_reset_tokens (
    email       VARCHAR(255) PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(0) NULL
);

CREATE TABLE cache (
    key         VARCHAR(255) PRIMARY KEY,
    value       TEXT NOT NULL,
    expiration  BIGINT NOT NULL
);
CREATE INDEX cache_expiration_index ON cache (expiration);

CREATE TABLE cache_locks (
    key         VARCHAR(255) PRIMARY KEY,
    owner       VARCHAR(255) NOT NULL,
    expiration  BIGINT NOT NULL
);
CREATE INDEX cache_locks_expiration_index ON cache_locks (expiration);

CREATE TABLE jobs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue         VARCHAR(255) NOT NULL,
    payload       TEXT NOT NULL,
    attempts      SMALLINT NOT NULL,
    reserved_at   INTEGER NULL,
    available_at  INTEGER NOT NULL,
    created_at    INTEGER NOT NULL
);
CREATE INDEX jobs_queue_index ON jobs (queue);

CREATE TABLE job_batches (
    id              VARCHAR(255) PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    total_jobs      INTEGER NOT NULL,
    pending_jobs    INTEGER NOT NULL,
    failed_jobs     INTEGER NOT NULL,
    failed_job_ids  TEXT NOT NULL,
    options         TEXT NULL,
    cancelled_at    INTEGER NULL,
    created_at      INTEGER NOT NULL,
    finished_at     INTEGER NULL
);

CREATE TABLE failed_jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(255) NOT NULL UNIQUE,
    connection  TEXT NOT NULL,
    queue       TEXT NOT NULL,
    payload     TEXT NOT NULL,
    exception   TEXT NOT NULL,
    failed_at   TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX failed_jobs_connection_queue_failed_at_index ON failed_jobs (connection, queue, failed_at);

-- Notifikasi in-app (Laravel database channel)
CREATE TABLE notifications (
    id               UUID PRIMARY KEY,
    type             VARCHAR(255) NOT NULL,
    notifiable_type  VARCHAR(255) NOT NULL,
    notifiable_id    BIGINT NOT NULL,
    data             TEXT NOT NULL,
    read_at          TIMESTAMP(0) NULL,
    created_at       TIMESTAMP(0) NULL,
    updated_at       TIMESTAMP(0) NULL
);
CREATE INDEX notifications_notifiable_index ON notifications (notifiable_type, notifiable_id);

-- =============================================================================
-- 2. ORGANISASI: DEPARTEMEN, LOKASI, KARYAWAN
-- =============================================================================

CREATE TABLE departments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(0) NULL,
    updated_at  TIMESTAMP(0) NULL,
    deleted_at  TIMESTAMP(0) NULL
);
CREATE UNIQUE INDEX departments_code_unique ON departments (code) WHERE deleted_at IS NULL;

CREATE TABLE locations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    address     TEXT NULL,
    parent_id   BIGINT NULL REFERENCES locations (id),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(0) NULL,
    updated_at  TIMESTAMP(0) NULL,
    deleted_at  TIMESTAMP(0) NULL,
    CONSTRAINT locations_parent_not_self CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE UNIQUE INDEX locations_code_unique ON locations (code) WHERE deleted_at IS NULL;
CREATE INDEX locations_parent_id_index ON locations (parent_id);

-- Master karyawan: sumber resmi identitas & struktur organisasi (approver = atasan langsung)
CREATE TABLE employees (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no          VARCHAR(30)  NOT NULL UNIQUE,
    name                 VARCHAR(150) NOT NULL,
    email                VARCHAR(150) NULL UNIQUE,
    phone                VARCHAR(30)  NULL,
    department_id        BIGINT NOT NULL REFERENCES departments (id),
    manager_employee_id  BIGINT NULL REFERENCES employees (id),
    job_title            VARCHAR(100) NULL,
    employment_status    VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    start_date           DATE NULL,
    end_date             DATE NULL,
    work_location_id     BIGINT NULL REFERENCES locations (id),
    created_at           TIMESTAMP(0) NULL,
    updated_at           TIMESTAMP(0) NULL,
    CONSTRAINT employees_status_check CHECK (employment_status IN ('ACTIVE', 'ON_LEAVE', 'INACTIVE')),
    CONSTRAINT employees_manager_not_self CHECK (manager_employee_id IS NULL OR manager_employee_id <> id),
    CONSTRAINT employees_dates_check CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);
CREATE INDEX employees_department_id_index ON employees (department_id);
CREATE INDEX employees_manager_employee_id_index ON employees (manager_employee_id);
CREATE INDEX employees_status_index ON employees (employment_status);

-- =============================================================================
-- 3. IDENTITAS & RBAC
-- =============================================================================

-- Akun login; opsional ditautkan ke tepat satu karyawan
CREATE TABLE users (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id        BIGINT NULL UNIQUE REFERENCES employees (id),
    name               VARCHAR(150) NOT NULL,
    email              VARCHAR(150) NOT NULL UNIQUE,
    email_verified_at  TIMESTAMP(0) NULL,
    password           VARCHAR(255) NOT NULL,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at      TIMESTAMP(0) NULL,
    remember_token     VARCHAR(100) NULL,
    created_at         TIMESTAMP(0) NULL,
    updated_at         TIMESTAMP(0) NULL
);

CREATE TABLE roles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)  NOT NULL UNIQUE,   -- slug, dipakai di kode
    display_name  VARCHAR(100) NOT NULL,
    description   TEXT NULL,
    is_system     BOOLEAN NOT NULL DEFAULT FALSE, -- role bawaan: tidak boleh dihapus
    created_at    TIMESTAMP(0) NULL,
    updated_at    TIMESTAMP(0) NULL
);

CREATE TABLE permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL UNIQUE,   -- contoh: asset.view
    display_name  VARCHAR(150) NOT NULL,
    group_name    VARCHAR(50)  NOT NULL,
    description   TEXT NULL,
    created_at    TIMESTAMP(0) NULL,
    updated_at    TIMESTAMP(0) NULL
);

CREATE TABLE permission_role (
    permission_id  BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    role_id        BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (permission_id, role_id)
);
CREATE INDEX permission_role_role_id_index ON permission_role (role_id);

CREATE TABLE role_user (
    role_id  BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    user_id  BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, user_id)
);
CREATE INDEX role_user_user_id_index ON role_user (user_id);

-- Konfigurasi aplikasi (mis. approver eskalasi)
CREATE TABLE settings (
    key          VARCHAR(100) PRIMARY KEY,
    value        TEXT NULL,
    description  TEXT NULL,
    updated_at   TIMESTAMP(0) NULL
);

-- Penomoran dokumen aman-konkurensi (SELECT ... FOR UPDATE)
CREATE TABLE number_sequences (
    key         VARCHAR(50) PRIMARY KEY,
    last_value  BIGINT NOT NULL DEFAULT 0,
    updated_at  TIMESTAMP(0) NULL
);

-- =============================================================================
-- 4. MASTER ASET: KATEGORI & VENDOR
-- =============================================================================

CREATE TABLE asset_categories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(10)  NOT NULL,   -- prefix asset tag, mis. LPT
    name                VARCHAR(150) NOT NULL,
    description         TEXT NULL,
    useful_life_months  INTEGER NULL CHECK (useful_life_months IS NULL OR useful_life_months > 0),
    requires_serial     BOOLEAN NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP(0) NULL,
    updated_at          TIMESTAMP(0) NULL,
    deleted_at          TIMESTAMP(0) NULL
);
CREATE UNIQUE INDEX asset_categories_code_unique ON asset_categories (code) WHERE deleted_at IS NULL;

CREATE TABLE vendors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(20)  NOT NULL,
    name            VARCHAR(150) NOT NULL,
    contact_person  VARCHAR(100) NULL,
    phone           VARCHAR(30)  NULL,
    email           VARCHAR(150) NULL,
    address         TEXT NULL,
    tax_number      VARCHAR(30)  NULL,
    notes           TEXT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(0) NULL,
    updated_at      TIMESTAMP(0) NULL,
    deleted_at      TIMESTAMP(0) NULL
);
CREATE UNIQUE INDEX vendors_code_unique ON vendors (code) WHERE deleted_at IS NULL;

-- =============================================================================
-- 5. APPROVAL (entitas bersama untuk semua jenis permintaan)
-- =============================================================================

CREATE TABLE approval_requests (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type           VARCHAR(20) NOT NULL,
    requester_employee_id  BIGINT NOT NULL REFERENCES employees (id),
    submitted_by_user_id   BIGINT NULL REFERENCES users (id),
    status                 VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    submitted_at           TIMESTAMP(0) NULL,
    closed_at              TIMESTAMP(0) NULL,
    created_at             TIMESTAMP(0) NULL,
    updated_at             TIMESTAMP(0) NULL,
    CONSTRAINT approval_requests_type_check CHECK (request_type IN ('PROCUREMENT', 'ASSIGNMENT', 'LOAN', 'LOAN_EXTENSION', 'DISPOSAL')),
    CONSTRAINT approval_requests_status_check CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);
CREATE INDEX approval_requests_status_index ON approval_requests (status);
CREATE INDEX approval_requests_requester_index ON approval_requests (requester_employee_id);

CREATE TABLE approval_steps (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_request_id   BIGINT NOT NULL REFERENCES approval_requests (id),
    step_order            SMALLINT NOT NULL DEFAULT 1,
    approver_employee_id  BIGINT NOT NULL REFERENCES employees (id),  -- snapshot saat submit
    approver_source       VARCHAR(20) NOT NULL DEFAULT 'MANAGER',
    status                VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    comment               TEXT NULL,
    decided_at            TIMESTAMP(0) NULL,
    decided_by_user_id    BIGINT NULL REFERENCES users (id),
    created_at            TIMESTAMP(0) NULL,
    updated_at            TIMESTAMP(0) NULL,
    CONSTRAINT approval_steps_order_unique UNIQUE (approval_request_id, step_order),
    CONSTRAINT approval_steps_source_check CHECK (approver_source IN ('MANAGER', 'ESCALATION')),
    CONSTRAINT approval_steps_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT approval_steps_reject_comment CHECK (status <> 'REJECTED' OR (comment IS NOT NULL AND length(trim(comment)) > 0)),
    CONSTRAINT approval_steps_decided_check CHECK (status IN ('PENDING', 'CANCELLED') OR decided_at IS NOT NULL)
);
CREATE INDEX approval_steps_approver_status_index ON approval_steps (approver_employee_id, status);

-- =============================================================================
-- 6. PROCUREMENT
-- =============================================================================

CREATE TABLE procurement_requests (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no             VARCHAR(30) NOT NULL UNIQUE,
    approval_request_id    BIGINT NULL UNIQUE REFERENCES approval_requests (id),
    requester_employee_id  BIGINT NOT NULL REFERENCES employees (id),
    created_by_user_id     BIGINT NULL REFERENCES users (id),
    department_id          BIGINT NOT NULL REFERENCES departments (id),
    title                  VARCHAR(200) NOT NULL,
    justification          TEXT NOT NULL,
    needed_by              DATE NULL,
    estimated_total        NUMERIC(18, 2) NOT NULL DEFAULT 0,
    status                 VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    vendor_id              BIGINT NULL REFERENCES vendors (id),
    po_number              VARCHAR(50) NULL,
    ordered_at             TIMESTAMP(0) NULL,
    ordered_by_user_id     BIGINT NULL REFERENCES users (id),
    submitted_at           TIMESTAMP(0) NULL,
    completed_at           TIMESTAMP(0) NULL,
    closing_note           TEXT NULL,
    cancelled_at           TIMESTAMP(0) NULL,
    created_at             TIMESTAMP(0) NULL,
    updated_at             TIMESTAMP(0) NULL,
    CONSTRAINT procurement_requests_status_check CHECK (status IN
        ('DRAFT', 'PENDING_APPROVAL', 'REJECTED', 'APPROVED', 'ORDERED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')),
    CONSTRAINT procurement_requests_total_check CHECK (estimated_total >= 0)
);
CREATE INDEX procurement_requests_status_index ON procurement_requests (status);
CREATE INDEX procurement_requests_requester_index ON procurement_requests (requester_employee_id);

CREATE TABLE procurement_request_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    procurement_request_id  BIGINT NOT NULL REFERENCES procurement_requests (id) ON DELETE CASCADE,
    asset_category_id       BIGINT NOT NULL REFERENCES asset_categories (id),
    item_name               VARCHAR(200) NOT NULL,
    specification           TEXT NULL,
    quantity                INTEGER NOT NULL,
    estimated_unit_price    NUMERIC(18, 2) NOT NULL DEFAULT 0,
    quantity_received       INTEGER NOT NULL DEFAULT 0,
    quantity_rejected       INTEGER NOT NULL DEFAULT 0,
    created_at              TIMESTAMP(0) NULL,
    updated_at              TIMESTAMP(0) NULL,
    CONSTRAINT pri_quantity_check CHECK (quantity > 0),
    CONSTRAINT pri_price_check CHECK (estimated_unit_price >= 0),
    CONSTRAINT pri_received_check CHECK (quantity_received >= 0 AND quantity_received <= quantity),
    CONSTRAINT pri_rejected_check CHECK (quantity_rejected >= 0)
);
CREATE INDEX procurement_request_items_request_index ON procurement_request_items (procurement_request_id);

-- Penerimaan barang (bisa bertahap / parsial)
CREATE TABLE procurement_receipts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no              VARCHAR(30) NOT NULL UNIQUE,
    procurement_request_id  BIGINT NOT NULL REFERENCES procurement_requests (id),
    received_at             TIMESTAMP(0) NOT NULL,
    received_by_user_id     BIGINT NULL REFERENCES users (id),
    delivery_note_no        VARCHAR(50) NULL,
    notes                   TEXT NULL,
    created_at              TIMESTAMP(0) NULL,
    updated_at              TIMESTAMP(0) NULL
);
CREATE INDEX procurement_receipts_request_index ON procurement_receipts (procurement_request_id);

CREATE TABLE procurement_receipt_items (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    procurement_receipt_id       BIGINT NOT NULL REFERENCES procurement_receipts (id) ON DELETE CASCADE,
    procurement_request_item_id  BIGINT NOT NULL REFERENCES procurement_request_items (id),
    quantity_accepted            INTEGER NOT NULL DEFAULT 0 CHECK (quantity_accepted >= 0),
    quantity_rejected            INTEGER NOT NULL DEFAULT 0 CHECK (quantity_rejected >= 0),
    exception_notes              TEXT NULL,   -- selisih / kerusakan
    created_at                   TIMESTAMP(0) NULL,
    updated_at                   TIMESTAMP(0) NULL
);

-- =============================================================================
-- 7. ASSET REGISTRY
-- =============================================================================

CREATE TABLE assets (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_tag                    VARCHAR(50)  NOT NULL UNIQUE,
    name                         VARCHAR(200) NOT NULL,
    asset_category_id            BIGINT NOT NULL REFERENCES asset_categories (id),
    procurement_request_item_id  BIGINT NULL REFERENCES procurement_request_items (id),
    procurement_receipt_id       BIGINT NULL REFERENCES procurement_receipts (id),
    vendor_id                    BIGINT NULL REFERENCES vendors (id),
    department_id                BIGINT NULL REFERENCES departments (id),
    location_id                  BIGINT NOT NULL REFERENCES locations (id),
    brand                        VARCHAR(100) NULL,
    model                        VARCHAR(100) NULL,
    serial_number                VARCHAR(100) NULL,
    specification                TEXT NULL,
    status                       VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    condition                    VARCHAR(20) NOT NULL DEFAULT 'GOOD',
    purchase_date                DATE NULL,
    purchase_cost                NUMERIC(18, 2) NULL CHECK (purchase_cost IS NULL OR purchase_cost >= 0),
    warranty_end_date            DATE NULL,
    notes                        TEXT NULL,
    created_at                   TIMESTAMP(0) NULL,
    updated_at                   TIMESTAMP(0) NULL,
    CONSTRAINT assets_status_check CHECK (status IN
        ('AVAILABLE', 'ASSIGNED', 'ON_LOAN', 'IN_REPAIR', 'PENDING_DISPOSAL', 'DISPOSED', 'LOST')),
    CONSTRAINT assets_condition_check CHECK (condition IN ('GOOD', 'FAIR', 'POOR', 'DAMAGED'))
);
CREATE UNIQUE INDEX assets_serial_number_unique ON assets (serial_number) WHERE serial_number IS NOT NULL;
CREATE INDEX assets_status_index ON assets (status);
CREATE INDEX assets_category_index ON assets (asset_category_id);
CREATE INDEX assets_location_index ON assets (location_id);

-- Histori domain aset (append-only)
CREATE TABLE asset_events (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id                  BIGINT NOT NULL REFERENCES assets (id),
    event_type                VARCHAR(40) NOT NULL,
    from_status               VARCHAR(20) NULL,
    to_status                 VARCHAR(20) NULL,
    from_location_id          BIGINT NULL REFERENCES locations (id),
    to_location_id            BIGINT NULL REFERENCES locations (id),
    related_employee_id       BIGINT NULL REFERENCES employees (id),  -- penerima / peminjam
    performed_by_employee_id  BIGINT NULL REFERENCES employees (id),
    performed_by_user_id      BIGINT NULL REFERENCES users (id),
    reference_type            VARCHAR(40) NULL,
    reference_id              BIGINT NULL,
    notes                     TEXT NULL,
    metadata                  JSONB NULL,
    occurred_at               TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at                TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX asset_events_asset_occurred_index ON asset_events (asset_id, occurred_at DESC);

-- =============================================================================
-- 8. ASSIGNMENT (penugasan jangka panjang)
-- =============================================================================

CREATE TABLE assignment_requests (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no             VARCHAR(30) NOT NULL UNIQUE,
    approval_request_id    BIGINT NULL UNIQUE REFERENCES approval_requests (id),
    requester_employee_id  BIGINT NOT NULL REFERENCES employees (id),
    created_by_user_id     BIGINT NULL REFERENCES users (id),
    recipient_employee_id  BIGINT NOT NULL REFERENCES employees (id),
    location_id            BIGINT NOT NULL REFERENCES locations (id),
    purpose                TEXT NOT NULL,
    start_date             DATE NOT NULL,
    status                 VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    submitted_at           TIMESTAMP(0) NULL,
    fulfilled_at           TIMESTAMP(0) NULL,
    cancelled_at           TIMESTAMP(0) NULL,
    created_at             TIMESTAMP(0) NULL,
    updated_at             TIMESTAMP(0) NULL,
    CONSTRAINT assignment_requests_status_check CHECK (status IN
        ('DRAFT', 'PENDING_APPROVAL', 'REJECTED', 'APPROVED', 'FULFILLED', 'CANCELLED'))
);
CREATE INDEX assignment_requests_status_index ON assignment_requests (status);

CREATE TABLE assignment_request_items (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_request_id  BIGINT NOT NULL REFERENCES assignment_requests (id) ON DELETE CASCADE,
    asset_id               BIGINT NOT NULL REFERENCES assets (id),
    created_at             TIMESTAMP(0) NULL,
    updated_at             TIMESTAMP(0) NULL,
    CONSTRAINT assignment_request_items_unique UNIQUE (assignment_request_id, asset_id)
);
CREATE INDEX assignment_request_items_asset_index ON assignment_request_items (asset_id);

CREATE TABLE asset_assignments (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id               BIGINT NOT NULL REFERENCES assets (id),
    employee_id            BIGINT NOT NULL REFERENCES employees (id),
    assignment_request_id  BIGINT NULL REFERENCES assignment_requests (id),
    location_id            BIGINT NULL REFERENCES locations (id),
    assigned_at            TIMESTAMP(0) NOT NULL,
    assigned_by_user_id    BIGINT NULL REFERENCES users (id),
    condition_out          VARCHAR(20) NOT NULL,
    handover_document_no   VARCHAR(50) NULL,
    handover_notes         TEXT NULL,
    returned_at            TIMESTAMP(0) NULL,
    returned_by_user_id    BIGINT NULL REFERENCES users (id),
    condition_in           VARCHAR(20) NULL,
    return_notes           TEXT NULL,
    created_at             TIMESTAMP(0) NULL,
    updated_at             TIMESTAMP(0) NULL,
    CONSTRAINT asset_assignments_cond_out_check CHECK (condition_out IN ('GOOD', 'FAIR', 'POOR', 'DAMAGED')),
    CONSTRAINT asset_assignments_cond_in_check CHECK (condition_in IS NULL OR condition_in IN ('GOOD', 'FAIR', 'POOR', 'DAMAGED')),
    CONSTRAINT asset_assignments_dates_check CHECK (returned_at IS NULL OR returned_at >= assigned_at)
);
-- Satu aset maksimal satu assignment aktif
CREATE UNIQUE INDEX asset_assignments_one_active ON asset_assignments (asset_id) WHERE returned_at IS NULL;
CREATE INDEX asset_assignments_employee_index ON asset_assignments (employee_id);

-- =============================================================================
-- 9. PEMINJAMAN ASET (LOAN)
-- =============================================================================

CREATE TABLE asset_loan_requests (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no             VARCHAR(30) NOT NULL UNIQUE,
    approval_request_id    BIGINT NULL UNIQUE REFERENCES approval_requests (id),
    requester_employee_id  BIGINT NOT NULL REFERENCES employees (id),
    created_by_user_id     BIGINT NULL REFERENCES users (id),
    borrower_employee_id   BIGINT NOT NULL REFERENCES employees (id),
    usage_location_id      BIGINT NULL REFERENCES locations (id),
    purpose                TEXT NOT NULL,
    start_date             DATE NOT NULL,
    due_date               DATE NOT NULL,
    status                 VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    submitted_at           TIMESTAMP(0) NULL,
    fulfilled_at           TIMESTAMP(0) NULL,
    cancelled_at           TIMESTAMP(0) NULL,
    created_at             TIMESTAMP(0) NULL,
    updated_at             TIMESTAMP(0) NULL,
    CONSTRAINT asset_loan_requests_status_check CHECK (status IN
        ('DRAFT', 'PENDING_APPROVAL', 'REJECTED', 'APPROVED', 'FULFILLED', 'CANCELLED')),
    CONSTRAINT asset_loan_requests_dates_check CHECK (due_date >= start_date)
);
CREATE INDEX asset_loan_requests_status_index ON asset_loan_requests (status);

CREATE TABLE asset_loan_request_items (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_loan_request_id  BIGINT NOT NULL REFERENCES asset_loan_requests (id) ON DELETE CASCADE,
    asset_id               BIGINT NOT NULL REFERENCES assets (id),
    created_at             TIMESTAMP(0) NULL,
    updated_at             TIMESTAMP(0) NULL,
    CONSTRAINT asset_loan_request_items_unique UNIQUE (asset_loan_request_id, asset_id)
);
CREATE INDEX asset_loan_request_items_asset_index ON asset_loan_request_items (asset_id);

CREATE TABLE asset_loans (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id                BIGINT NOT NULL REFERENCES assets (id),
    borrower_employee_id    BIGINT NOT NULL REFERENCES employees (id),
    asset_loan_request_id   BIGINT NULL REFERENCES asset_loan_requests (id),
    usage_location_id       BIGINT NULL REFERENCES locations (id),
    checked_out_at          TIMESTAMP(0) NOT NULL,
    checked_out_by_user_id  BIGINT NULL REFERENCES users (id),
    due_at                  TIMESTAMP(0) NOT NULL,
    original_due_at         TIMESTAMP(0) NOT NULL,
    returned_at             TIMESTAMP(0) NULL,
    returned_by_user_id     BIGINT NULL REFERENCES users (id),
    condition_out           VARCHAR(20) NOT NULL,
    condition_in            VARCHAR(20) NULL,
    checkout_notes          TEXT NULL,
    return_notes            TEXT NULL,
    is_late                 BOOLEAN NOT NULL DEFAULT FALSE,
    status                  VARCHAR(20) NOT NULL DEFAULT 'CHECKED_OUT',
    created_at              TIMESTAMP(0) NULL,
    updated_at              TIMESTAMP(0) NULL,
    CONSTRAINT asset_loans_status_check CHECK (status IN ('CHECKED_OUT', 'OVERDUE', 'RETURNED', 'CANCELLED')),
    CONSTRAINT asset_loans_cond_out_check CHECK (condition_out IN ('GOOD', 'FAIR', 'POOR', 'DAMAGED')),
    CONSTRAINT asset_loans_cond_in_check CHECK (condition_in IS NULL OR condition_in IN ('GOOD', 'FAIR', 'POOR', 'DAMAGED')),
    CONSTRAINT asset_loans_due_check CHECK (due_at > checked_out_at),
    CONSTRAINT asset_loans_return_check CHECK (returned_at IS NULL OR returned_at >= checked_out_at),
    CONSTRAINT asset_loans_returned_status CHECK ((status = 'RETURNED') = (returned_at IS NOT NULL)),
    -- Periode pemakaian satu aset tidak boleh tumpang tindih
    CONSTRAINT asset_loans_no_overlap EXCLUDE USING gist (
        asset_id WITH =,
        tsrange(checked_out_at, COALESCE(returned_at, due_at), '[)') WITH &&
    ) WHERE (status <> 'CANCELLED')
);
-- Satu aset maksimal satu loan aktif
CREATE UNIQUE INDEX asset_loans_one_active ON asset_loans (asset_id) WHERE status IN ('CHECKED_OUT', 'OVERDUE');
CREATE INDEX asset_loans_borrower_index ON asset_loans (borrower_employee_id);
CREATE INDEX asset_loans_status_due_index ON asset_loans (status, due_at);

-- Perpanjangan due date (melalui approval; histori due date tetap tersimpan)
CREATE TABLE loan_extension_requests (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no             VARCHAR(30) NOT NULL UNIQUE,
    approval_request_id    BIGINT NULL UNIQUE REFERENCES approval_requests (id),
    asset_loan_id          BIGINT NOT NULL REFERENCES asset_loans (id),
    requester_employee_id  BIGINT NOT NULL REFERENCES employees (id),
    created_by_user_id     BIGINT NULL REFERENCES users (id),
    current_due_at         TIMESTAMP(0) NOT NULL,
    requested_due_at       TIMESTAMP(0) NOT NULL,
    reason                 TEXT NOT NULL,
    status                 VARCHAR(20) NOT NULL DEFAULT 'PENDING_APPROVAL',
    applied_at             TIMESTAMP(0) NULL,
    cancelled_at           TIMESTAMP(0) NULL,
    created_at             TIMESTAMP(0) NULL,
    updated_at             TIMESTAMP(0) NULL,
    CONSTRAINT loan_ext_status_check CHECK (status IN ('PENDING_APPROVAL', 'REJECTED', 'APPROVED', 'CANCELLED')),
    CONSTRAINT loan_ext_dates_check CHECK (requested_due_at > current_due_at)
);
CREATE UNIQUE INDEX loan_ext_one_pending ON loan_extension_requests (asset_loan_id) WHERE status = 'PENDING_APPROVAL';

-- =============================================================================
-- 10. DISPOSAL
-- =============================================================================

CREATE TABLE disposal_requests (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no             VARCHAR(30) NOT NULL UNIQUE,
    approval_request_id    BIGINT NULL UNIQUE REFERENCES approval_requests (id),
    asset_id               BIGINT NOT NULL REFERENCES assets (id),
    requester_employee_id  BIGINT NOT NULL REFERENCES employees (id),
    created_by_user_id     BIGINT NULL REFERENCES users (id),
    reason_type            VARCHAR(20) NOT NULL,
    reason                 TEXT NOT NULL,
    condition_description  TEXT NULL,
    planned_method         VARCHAR(20) NOT NULL,
    status                 VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    asset_status_before    VARCHAR(20) NULL,
    submitted_at           TIMESTAMP(0) NULL,
    cancelled_at           TIMESTAMP(0) NULL,
    executed_at            DATE NULL,
    executed_by_user_id    BIGINT NULL REFERENCES users (id),
    actual_method          VARCHAR(20) NULL,
    disposal_recipient     VARCHAR(200) NULL,
    proceeds_amount        NUMERIC(18, 2) NULL CHECK (proceeds_amount IS NULL OR proceeds_amount >= 0),
    execution_notes        TEXT NULL,
    completed_at           TIMESTAMP(0) NULL,
    created_at             TIMESTAMP(0) NULL,
    updated_at             TIMESTAMP(0) NULL,
    CONSTRAINT disposal_requests_status_check CHECK (status IN
        ('DRAFT', 'PENDING_APPROVAL', 'REJECTED', 'APPROVED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT disposal_requests_reason_check CHECK (reason_type IN ('DAMAGED', 'OBSOLETE', 'UNECONOMICAL', 'LOST', 'OTHER')),
    CONSTRAINT disposal_requests_method_check CHECK (planned_method IN ('SALE', 'DONATION', 'SCRAP', 'RECYCLE', 'WRITE_OFF', 'OTHER')),
    CONSTRAINT disposal_requests_actual_method_check CHECK (actual_method IS NULL OR actual_method IN ('SALE', 'DONATION', 'SCRAP', 'RECYCLE', 'WRITE_OFF', 'OTHER'))
);
-- Satu aset maksimal satu disposal terbuka
CREATE UNIQUE INDEX disposal_requests_one_open ON disposal_requests (asset_id) WHERE status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED');
CREATE INDEX disposal_requests_status_index ON disposal_requests (status);

-- =============================================================================
-- 11. LAMPIRAN & AUDIT
-- =============================================================================

CREATE TABLE attachments (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attachable_type      VARCHAR(50) NOT NULL,
    attachable_id        BIGINT NOT NULL,
    category             VARCHAR(30) NOT NULL DEFAULT 'OTHER',
    original_name        VARCHAR(255) NOT NULL,
    stored_path          VARCHAR(500) NOT NULL,
    mime_type            VARCHAR(150) NULL,
    size_bytes           BIGINT NOT NULL DEFAULT 0,
    uploaded_by_user_id  BIGINT NULL REFERENCES users (id),
    created_at           TIMESTAMP(0) NULL,
    updated_at           TIMESTAMP(0) NULL
);
CREATE INDEX attachments_attachable_index ON attachments (attachable_type, attachable_id);

CREATE TABLE audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NULL REFERENCES users (id),
    action          VARCHAR(50) NOT NULL,
    auditable_type  VARCHAR(100) NULL,
    auditable_id    BIGINT NULL,
    old_values      JSONB NULL,
    new_values      JSONB NULL,
    ip_address      VARCHAR(45) NULL,
    user_agent      TEXT NULL,
    url             TEXT NULL,
    request_id      VARCHAR(64) NULL,
    created_at      TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX audit_logs_auditable_index ON audit_logs (auditable_type, auditable_id);
CREATE INDEX audit_logs_user_index ON audit_logs (user_id);
CREATE INDEX audit_logs_created_at_index ON audit_logs (created_at DESC);

-- =============================================================================
-- 12. TRIGGER INTEGRITAS
-- =============================================================================

-- a) Tabel append-only: asset_events & audit_logs tidak boleh diubah/dihapus
CREATE OR REPLACE FUNCTION fn_prevent_modify_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Tabel % bersifat append-only: % tidak diizinkan', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_asset_events_append_only
    BEFORE UPDATE OR DELETE ON asset_events
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_modify_append_only();

CREATE TRIGGER trg_audit_logs_append_only
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION fn_prevent_modify_append_only();

-- b) Aset: tidak boleh hard-delete; status DISPOSED bersifat final
CREATE OR REPLACE FUNCTION fn_assets_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Aset % tidak boleh dihapus dari database', OLD.asset_tag
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF OLD.status = 'DISPOSED' AND NEW.status IS DISTINCT FROM 'DISPOSED' THEN
        RAISE EXCEPTION 'Aset % sudah DISPOSED; status final tidak dapat diubah', OLD.asset_tag
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_assets_guard
    BEFORE UPDATE OR DELETE ON assets
    FOR EACH ROW EXECUTE FUNCTION fn_assets_guard();

-- c) Approval step: keputusan immutable; approver harus berbeda dari requester
CREATE OR REPLACE FUNCTION fn_approval_steps_guard() RETURNS trigger AS $$
DECLARE
    v_requester BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Approval step tidak boleh dihapus' USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF OLD.status <> 'PENDING' THEN
            RAISE EXCEPTION 'Keputusan approval step % sudah final', OLD.id
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        IF NEW.approver_employee_id <> OLD.approver_employee_id THEN
            RAISE EXCEPTION 'Snapshot approver tidak boleh diubah' USING ERRCODE = 'integrity_constraint_violation';
        END IF;
    END IF;

    SELECT requester_employee_id INTO v_requester FROM approval_requests WHERE id = NEW.approval_request_id;
    IF v_requester = NEW.approver_employee_id THEN
        RAISE EXCEPTION 'Approver tidak boleh sama dengan requester' USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_approval_steps_guard
    BEFORE INSERT OR UPDATE OR DELETE ON approval_steps
    FOR EACH ROW EXECUTE FUNCTION fn_approval_steps_guard();

-- d) Approval request yang sudah final (APPROVED/REJECTED/CANCELLED) tidak boleh berubah status
CREATE OR REPLACE FUNCTION fn_approval_requests_guard() RETURNS trigger AS $$
BEGIN
    IF OLD.status IN ('APPROVED', 'REJECTED', 'CANCELLED') AND NEW.status IS DISTINCT FROM OLD.status THEN
        RAISE EXCEPTION 'Approval request % sudah final (%)', OLD.id, OLD.status
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_approval_requests_guard
    BEFORE UPDATE ON approval_requests
    FOR EACH ROW EXECUTE FUNCTION fn_approval_requests_guard();

-- e) Satu aset tidak boleh memiliki assignment aktif DAN loan aktif bersamaan
CREATE OR REPLACE FUNCTION fn_asset_assignment_loan_exclusive() RETURNS trigger AS $$
BEGIN
    IF TG_TABLE_NAME = 'asset_assignments' AND NEW.returned_at IS NULL THEN
        IF EXISTS (SELECT 1 FROM asset_loans WHERE asset_id = NEW.asset_id AND status IN ('CHECKED_OUT', 'OVERDUE')) THEN
            RAISE EXCEPTION 'Aset % sedang dipinjam; tidak dapat di-assign', NEW.asset_id
                USING ERRCODE = 'check_violation';
        END IF;
    ELSIF TG_TABLE_NAME = 'asset_loans' AND NEW.status IN ('CHECKED_OUT', 'OVERDUE') THEN
        IF EXISTS (SELECT 1 FROM asset_assignments WHERE asset_id = NEW.asset_id AND returned_at IS NULL) THEN
            RAISE EXCEPTION 'Aset % sedang ditugaskan; tidak dapat dipinjam', NEW.asset_id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_asset_assignments_exclusive
    BEFORE INSERT OR UPDATE ON asset_assignments
    FOR EACH ROW EXECUTE FUNCTION fn_asset_assignment_loan_exclusive();

CREATE TRIGGER trg_asset_loans_exclusive
    BEFORE INSERT OR UPDATE ON asset_loans
    FOR EACH ROW EXECUTE FUNCTION fn_asset_assignment_loan_exclusive();

-- =============================================================================
-- 13. DATA RBAC
-- @@SEED-START@@ (penanda: migration menjalankan bagian di atas, seeder bagian di bawah)
-- =============================================================================

INSERT INTO roles (name, display_name, description, is_system, created_at, updated_at) VALUES
('staff',       'Staff / Requester',    'Membuat permintaan procurement, assignment, peminjaman, dan disposal; melihat status & aset tanggung jawabnya.', TRUE, NOW(), NOW()),
('manager',     'Manager / Approver',   'Menyetujui/menolak permintaan staff dalam cakupan tim, disertai catatan keputusan.', TRUE, NOW(), NOW()),
('asset_admin', 'Asset Administrator',  'Mengelola master aset, menindaklanjuti permintaan yang disetujui, penerimaan, serah-terima, pengembalian, dan disposal.', TRUE, NOW(), NOW()),
('sys_admin',   'System Administrator', 'Mengelola akun, role, konfigurasi, dan referensi organisasi. Tidak otomatis berwenang menyetujui transaksi.', TRUE, NOW(), NOW()),
('auditor',     'Auditor / Read-only',  'Melihat data dan riwayat tanpa mengubah transaksi.', TRUE, NOW(), NOW());

INSERT INTO permissions (name, display_name, group_name, created_at, updated_at) VALUES
-- Dashboard & laporan
('dashboard.view',             'Lihat dashboard',                        'Dashboard',   NOW(), NOW()),
('report.view',                'Lihat & export laporan',                 'Laporan',     NOW(), NOW()),
-- Asset registry
('asset.view',                 'Lihat katalog aset',                     'Aset',        NOW(), NOW()),
('asset.create',               'Registrasi aset manual',                 'Aset',        NOW(), NOW()),
('asset.update',               'Ubah data aset',                         'Aset',        NOW(), NOW()),
('asset.status',               'Ubah status operasional (perbaikan/hilang)', 'Aset',    NOW(), NOW()),
-- Procurement
('procurement.create',         'Ajukan procurement',                     'Procurement', NOW(), NOW()),
('procurement.view_all',       'Lihat semua procurement',                'Procurement', NOW(), NOW()),
('procurement.order',          'Proses pemesanan (vendor/PO)',           'Procurement', NOW(), NOW()),
('procurement.receive',        'Terima barang & registrasi aset',        'Procurement', NOW(), NOW()),
-- Assignment
('assignment.create',          'Ajukan assignment',                      'Assignment',  NOW(), NOW()),
('assignment.create_for_others','Ajukan assignment untuk karyawan lain', 'Assignment',  NOW(), NOW()),
('assignment.view_all',        'Lihat semua assignment',                 'Assignment',  NOW(), NOW()),
('assignment.handover',        'Serah-terima assignment',                'Assignment',  NOW(), NOW()),
('assignment.return',          'Catat pengembalian assignment',          'Assignment',  NOW(), NOW()),
-- Loan
('loan.create',                'Ajukan peminjaman',                      'Peminjaman',  NOW(), NOW()),
('loan.create_for_others',     'Ajukan peminjaman atas nama karyawan',   'Peminjaman',  NOW(), NOW()),
('loan.view_all',              'Lihat semua peminjaman',                 'Peminjaman',  NOW(), NOW()),
('loan.checkout',              'Serah-terima peminjaman',                'Peminjaman',  NOW(), NOW()),
('loan.return',                'Catat pengembalian peminjaman',          'Peminjaman',  NOW(), NOW()),
('loan.extend',                'Ajukan perpanjangan peminjaman',         'Peminjaman',  NOW(), NOW()),
-- Disposal
('disposal.create',            'Ajukan disposal',                        'Disposal',    NOW(), NOW()),
('disposal.view_all',          'Lihat semua disposal',                   'Disposal',    NOW(), NOW()),
('disposal.execute',           'Eksekusi disposal',                      'Disposal',    NOW(), NOW()),
-- Approval
('approval.decide',            'Memutuskan approval (approve/reject)',   'Approval',    NOW(), NOW()),
-- Master & administrasi
('employee.view',              'Lihat master karyawan',                  'Master Data', NOW(), NOW()),
('employee.manage',            'Kelola master karyawan',                 'Master Data', NOW(), NOW()),
('master.view',                'Lihat master referensi',                 'Master Data', NOW(), NOW()),
('master.manage',              'Kelola departemen/lokasi/kategori/vendor','Master Data', NOW(), NOW()),
('user.manage',                'Kelola akun pengguna',                   'Administrasi', NOW(), NOW()),
('role.manage',                'Kelola role & permission',               'Administrasi', NOW(), NOW()),
('setting.manage',             'Kelola konfigurasi aplikasi',            'Administrasi', NOW(), NOW()),
('audit.view',                 'Lihat audit log',                        'Administrasi', NOW(), NOW());

-- Pemetaan role → permission
INSERT INTO permission_role (permission_id, role_id)
SELECT p.id, r.id
FROM (VALUES
    -- staff
    ('staff', 'dashboard.view'), ('staff', 'asset.view'), ('staff', 'procurement.create'),
    ('staff', 'assignment.create'), ('staff', 'loan.create'), ('staff', 'loan.extend'), ('staff', 'disposal.create'),
    -- manager (= staff + approval)
    ('manager', 'dashboard.view'), ('manager', 'asset.view'), ('manager', 'procurement.create'),
    ('manager', 'assignment.create'), ('manager', 'loan.create'), ('manager', 'loan.extend'), ('manager', 'disposal.create'),
    ('manager', 'approval.decide'), ('manager', 'report.view'), ('manager', 'employee.view'),
    -- asset administrator
    ('asset_admin', 'dashboard.view'), ('asset_admin', 'report.view'),
    ('asset_admin', 'asset.view'), ('asset_admin', 'asset.create'), ('asset_admin', 'asset.update'), ('asset_admin', 'asset.status'),
    ('asset_admin', 'procurement.create'), ('asset_admin', 'procurement.view_all'), ('asset_admin', 'procurement.order'), ('asset_admin', 'procurement.receive'),
    ('asset_admin', 'assignment.create'), ('asset_admin', 'assignment.create_for_others'), ('asset_admin', 'assignment.view_all'),
    ('asset_admin', 'assignment.handover'), ('asset_admin', 'assignment.return'),
    ('asset_admin', 'loan.create'), ('asset_admin', 'loan.create_for_others'), ('asset_admin', 'loan.view_all'),
    ('asset_admin', 'loan.checkout'), ('asset_admin', 'loan.return'), ('asset_admin', 'loan.extend'),
    ('asset_admin', 'disposal.create'), ('asset_admin', 'disposal.view_all'), ('asset_admin', 'disposal.execute'),
    ('asset_admin', 'employee.view'), ('asset_admin', 'master.view'), ('asset_admin', 'master.manage'),
    -- system administrator (tanpa approval.decide)
    ('sys_admin', 'dashboard.view'), ('sys_admin', 'asset.view'),
    ('sys_admin', 'employee.view'), ('sys_admin', 'employee.manage'), ('sys_admin', 'master.view'), ('sys_admin', 'master.manage'),
    ('sys_admin', 'user.manage'), ('sys_admin', 'role.manage'), ('sys_admin', 'setting.manage'), ('sys_admin', 'audit.view'),
    -- auditor (read-only)
    ('auditor', 'dashboard.view'), ('auditor', 'report.view'), ('auditor', 'asset.view'),
    ('auditor', 'procurement.view_all'), ('auditor', 'assignment.view_all'), ('auditor', 'loan.view_all'), ('auditor', 'disposal.view_all'),
    ('auditor', 'employee.view'), ('auditor', 'master.view'), ('auditor', 'audit.view')
) AS m(role_name, permission_name)
JOIN roles r ON r.name = m.role_name
JOIN permissions p ON p.name = m.permission_name;

-- =============================================================================
-- 14. DATA AWAL (DEMO) — sesuaikan / hapus untuk produksi
-- =============================================================================

INSERT INTO departments (code, name, created_at, updated_at) VALUES
('BOD', 'Direksi',                NOW(), NOW()),
('IT',  'Information Technology', NOW(), NOW()),
('GA',  'General Affairs',        NOW(), NOW()),
('FIN', 'Finance & Accounting',   NOW(), NOW()),
('HR',  'Human Resources',        NOW(), NOW()),
('MKT', 'Marketing',              NOW(), NOW());

INSERT INTO locations (code, name, address, created_at, updated_at) VALUES
('HQ',  'Kantor Pusat',  'Jl. Jend. Sudirman Kav. 1, Jakarta', NOW(), NOW()),
('WH',  'Gudang Aset',   'Jl. Industri No. 8, Bekasi',         NOW(), NOW());
INSERT INTO locations (code, name, parent_id, created_at, updated_at)
SELECT v.code, v.name, (SELECT id FROM locations WHERE code = v.parent), NOW(), NOW()
FROM (VALUES
    ('HQ-L3',  'Kantor Pusat — Lantai 3', 'HQ'),
    ('HQ-L4',  'Kantor Pusat — Lantai 4', 'HQ'),
    ('HQ-SRV', 'Kantor Pusat — Server Room', 'HQ'),
    ('WH-A',   'Gudang Aset — Rak A', 'WH')
) AS v(code, name, parent);

INSERT INTO asset_categories (code, name, useful_life_months, requires_serial, created_at, updated_at) VALUES
('LPT', 'Laptop',            48, TRUE,  NOW(), NOW()),
('DSK', 'Desktop PC',        48, TRUE,  NOW(), NOW()),
('MON', 'Monitor',           60, TRUE,  NOW(), NOW()),
('PRN', 'Printer & Scanner', 60, TRUE,  NOW(), NOW()),
('NET', 'Perangkat Jaringan',60, TRUE,  NOW(), NOW()),
('PRJ', 'Proyektor',         60, TRUE,  NOW(), NOW()),
('PHN', 'Smartphone/Tablet', 36, TRUE,  NOW(), NOW()),
('FUR', 'Furnitur',          96, FALSE, NOW(), NOW());

INSERT INTO vendors (code, name, contact_person, phone, email, created_at, updated_at) VALUES
('V-001', 'PT Mitra Teknologi Nusantara', 'Andi Wijaya', '021-5550101', 'sales@mitratek.test', NOW(), NOW()),
('V-002', 'CV Sarana Kantor Prima',       'Rina Kusuma', '021-5550202', 'order@saranakantor.test', NOW(), NOW());

-- Karyawan (atasan disisipkan setelah bawahannya direferensikan melalui employee_no)
INSERT INTO employees (employee_no, name, email, department_id, job_title, work_location_id, start_date, created_at, updated_at)
SELECT v.no, v.name, v.email, (SELECT id FROM departments WHERE code = v.dept), v.title,
       (SELECT id FROM locations WHERE code = 'HQ'), DATE '2020-01-01', NOW(), NOW()
FROM (VALUES
    ('EMP-0001', 'Hendra Gunawan',  'direktur@kantorku.test',   'BOD', 'Direktur Operasional'),
    ('EMP-0002', 'Yusuf Pratama',   'sysadmin@kantorku.test',   'IT',  'System Administrator'),
    ('EMP-0003', 'Bambang Pratama', 'admin.aset@kantorku.test', 'GA',  'Asset Administrator'),
    ('EMP-0004', 'Dewi Lestari',    'manager.it@kantorku.test', 'IT',  'IT Manager'),
    ('EMP-0005', 'Siti Rahmawati',  'staff@kantorku.test',      'IT',  'Software Engineer'),
    ('EMP-0006', 'Agus Salim',      'auditor@kantorku.test',    'FIN', 'Internal Auditor'),
    ('EMP-0007', 'Dimas Satrio',    'dimas@kantorku.test',      'IT',  'Network Engineer')
) AS v(no, name, email, dept, title);

UPDATE employees e SET manager_employee_id = m.id
FROM (VALUES
    ('EMP-0002', 'EMP-0004'),
    ('EMP-0003', 'EMP-0001'),
    ('EMP-0004', 'EMP-0001'),
    ('EMP-0005', 'EMP-0004'),
    ('EMP-0006', 'EMP-0001'),
    ('EMP-0007', 'EMP-0004')
) AS v(emp_no, mgr_no)
JOIN employees m ON m.employee_no = v.mgr_no
WHERE e.employee_no = v.emp_no;

-- Akun login (EMP-0007 sengaja tanpa akun: tetap bisa menjadi penerima/peminjam)
INSERT INTO users (employee_id, name, email, password, is_active, email_verified_at, created_at, updated_at)
SELECT e.id, e.name, e.email, '$2y$12$Pie9wTCeeGIcYCby497sF.iGQYUBuk0qNjVvl23vqsIOP4kJysypa', TRUE, NOW(), NOW(), NOW()
FROM employees e
WHERE e.employee_no IN ('EMP-0001', 'EMP-0002', 'EMP-0003', 'EMP-0004', 'EMP-0005', 'EMP-0006');

INSERT INTO role_user (role_id, user_id)
SELECT r.id, u.id
FROM (VALUES
    ('direktur@kantorku.test',   'manager'),
    ('sysadmin@kantorku.test',   'sys_admin'),
    ('admin.aset@kantorku.test', 'asset_admin'),
    ('admin.aset@kantorku.test', 'staff'),
    ('manager.it@kantorku.test', 'manager'),
    ('staff@kantorku.test',      'staff'),
    ('auditor@kantorku.test',    'auditor')
) AS v(email, role_name)
JOIN users u ON u.email = v.email
JOIN roles r ON r.name = v.role_name;

INSERT INTO settings (key, value, description, updated_at) VALUES
('app.company_name',               'PT Kantorku Indonesia', 'Nama perusahaan yang tampil di aplikasi', NOW()),
('approval.escalation_employee_id', (SELECT id::text FROM employees WHERE employee_no = 'EMP-0001'),
    'Approver pengganti bila atasan requester kosong, nonaktif, tidak memiliki akun approver, atau sama dengan requester', NOW()),
('loan.max_duration_days',         '30', 'Durasi maksimal peminjaman (hari)', NOW()),
('attachment.max_size_kb',         '5120', 'Ukuran maksimal lampiran (KB)', NOW());

-- Contoh aset tersedia
INSERT INTO assets (asset_tag, name, asset_category_id, vendor_id, location_id, brand, model, serial_number,
                    specification, status, condition, purchase_date, purchase_cost, warranty_end_date, created_at, updated_at)
SELECT v.tag, v.name, (SELECT id FROM asset_categories WHERE code = v.cat), (SELECT id FROM vendors WHERE code = 'V-001'),
       (SELECT id FROM locations WHERE code = v.loc), v.brand, v.model, v.sn, v.spec, 'AVAILABLE', 'GOOD',
       v.pdate::date, v.cost, v.wdate::date, NOW(), NOW()
FROM (VALUES
    ('LPT-2026-00001', 'Dell Latitude 7440',      'LPT', 'WH-A',   'Dell',   'Latitude 7440',  'DL7440-0001', 'Intel i7 13th Gen, 32GB RAM, 1TB SSD', '2026-01-15', 24500000, '2029-01-15'),
    ('LPT-2026-00002', 'Lenovo ThinkPad X1 Carbon','LPT', 'WH-A',   'Lenovo', 'X1 Carbon Gen 11','LNX1C-0002', 'Intel i7, 16GB RAM, 512GB SSD',        '2026-01-15', 27000000, '2029-01-15'),
    ('MON-2026-00001', 'Dell UltraSharp 27"',     'MON', 'WH-A',   'Dell',   'U2723QE',        'DLU27-0001',  '27 inch 4K IPS',                       '2026-02-01', 9500000,  '2029-02-01'),
    ('PRJ-2026-00001', 'Epson EB-X51',            'PRJ', 'HQ-L3',  'Epson',  'EB-X51',         'EPX51-0001',  '3800 lumens XGA',                      '2026-02-10', 7800000,  '2028-02-10'),
    ('NET-2026-00001', 'Cisco Catalyst 9200L',    'NET', 'HQ-SRV', 'Cisco',  'C9200L-48P',     'CSC92-0001',  '48 Port PoE+ Gigabit',                 '2026-03-01', 65000000, '2031-03-01')
) AS v(tag, name, cat, loc, brand, model, sn, spec, pdate, cost, wdate);

INSERT INTO asset_events (asset_id, event_type, to_status, to_location_id, notes, occurred_at, created_at)
SELECT id, 'REGISTERED', status, location_id, 'Data awal instalasi', NOW(), NOW() FROM assets;

INSERT INTO number_sequences (key, last_value, updated_at) VALUES
('ASSET-LPT-2026', 2, NOW()),
('ASSET-MON-2026', 1, NOW()),
('ASSET-PRJ-2026', 1, NOW()),
('ASSET-NET-2026', 1, NOW());

-- @@SEED-END@@
COMMIT;
